[phases.build]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate --noinput",
  "python manage.py loaddata principal/fixtures/planes.json || true",
  "python manage.py loaddata principal/fixtures/grupos.json || true"
]
