# Generated by Django 5.2.8 on 2025-12-22 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('orden', models.IntegerField(default=0)),
                ('es_principal', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Imagen del Producto',
                'verbose_name_plural': 'Imágenes del Producto',
                'ordering': ['orden'],
            },
        ),
    ]
