# Generated by Django 5.2.8 on 2025-12-22 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_imagenproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
