# Generated by Django 5.2.5 on 2026-05-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_producto_beneficios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
