# Generated by Django 5.2.5 on 2026-05-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudplan',
            name='activado',
            field=models.BooleanField(default=False, verbose_name='Activado'),
        ),
        migrations.AlterField(
            model_name='solicitudplan',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('activado', 'Activado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
