# Generated by Django 5.2.5 on 2025-11-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_clase_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Plan Azul', 'Plan Azul'), ('Plan Amarillo', 'Plan Amarillo'), ('Plan Verde', 'Plan Verde')], max_length=20, verbose_name='Plan')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje o Comentarios')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('procesado', models.BooleanField(default=False, verbose_name='Procesado')),
            ],
            options={
                'verbose_name': 'Solicitud de Plan',
                'verbose_name_plural': 'Solicitudes de Planes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
