# Generated by Django 5.2.5 on 2026-05-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_solicitudplan_activado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Plan')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio (CLP)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Plan de Membresía',
                'verbose_name_plural': 'Planes de Membresía',
                'ordering': ['precio'],
            },
        ),
        migrations.AddField(
            model_name='miembro',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='Email verificado'),
        ),
    ]
