# Generated by Django 5.2.5 on 2026-05-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_planmembresia_miembro_email_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudplan',
            name='fecha_fin_membresia',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento de membresía'),
        ),
        migrations.AddField(
            model_name='solicitudplan',
            name='fecha_inicio_membresia',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de membresía'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='correo',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='solicitudplan',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Correo Electrónico'),
        ),
    ]
