# Generated by Django 5.2.5 on 2026-05-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_solicitudplan_fecha_fin_membresia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudplan',
            name='plan',
            field=models.CharField(choices=[('Plan Trimestral', 'Plan Trimestral'), ('Plan Semestral', 'Plan Semestral'), ('Plan Anual', 'Plan Anual')], max_length=20, verbose_name='Plan'),
        ),
    ]
