# Generated by Django 5.2.8 on 2025-12-30 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias/')),
                ('comentario', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('participacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='participaciones.participacion')),
            ],
        ),
    ]
