# Generated by Django 5.2.8 on 2025-12-30 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participaciones', '0002_evidencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencia',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='evidencia',
            name='estado',
        ),
    ]
